---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: audio-to-text-i1731931533096
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-to-text-i1731931533096 
  name: audio-to-text-i1731931533096
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi