apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: audio-to-text-i1731931533096-gitops-repository
spec:
  url: https://github.com/jrichter-rhtap/audio-to-text-i1731931533096-gitops